name: Build and Release Expo App

permissions: 
  contents: write
  issues: write
  pull-requests: write
  discussions: write
  packages: write
  actions: write
  repository-projects: write

on:
  push:
    branches: [main, development]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: v1.0.${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      - name: Cache Node Modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
          
      - name: Install dependencies
        run: yarn install

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
          
      - name: Install dependencies
        run: yarn install
          
      - name: Install EAS CLI
        run: yarn global add eas-cli
        
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Create eas.json
        run: |
          cat > eas.json << 'EOL'
          {
            "cli": {
              "version": ">= 3.13.3",
              "appVersionSource": "remote"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "buildType": "apk",
                  "gradleCommand": ":app:assembleDebug"
                }
              },
              "preview": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              },
              "production": {
                "autoIncrement": true,
                "android": {
                  "buildType": "apk"
                }
              }
            }
          }
          EOL
          
      - name: Build Android app
        run: |
          rm -rf app-build
          mkdir -p app-build
          eas build --local \
          --non-interactive \
          --output=./app-build/app-release.apk \
          --platform=android \
          --profile=production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: app-build/app-release.apk
          retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: app-build
          
      - name: Create Tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate QR Code and Create Release
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            
            try {
              // Validation
              const apkPath = './app-build/app-release.apk';
              const version = `1.0.${process.env.GITHUB_RUN_NUMBER}`;
              if (!process.env.GITHUB_RUN_NUMBER) {
                throw new Error('GITHUB_RUN_NUMBER is not defined');
              }
              if (!fs.existsSync(apkPath)) {
                throw new Error('APK file not found');
              }
              
              // QR Configuration
              const qrConfig = {
                size: 300,
                margin: 1,
                dark: '000000',
                light: 'FFFFFF'
              };
              
              const downloadUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/releases/download/v1.0.${process.env.GITHUB_RUN_NUMBER}/ksms-mb-v1.0.${process.env.GITHUB_RUN_NUMBER}.apk`;
              
              // Generate QR Code URL
              const qrCodeUrl = `https://quickchart.io/qr?text=${encodeURIComponent(downloadUrl)}&size=${qrConfig.size}&margin=${qrConfig.margin}&dark=${qrConfig.dark}&light=${qrConfig.light}`;
              
              core.info('Creating release with QR code...');
              
              const releaseResponse = await github.rest.repos.createRelease({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: `v1.0.${process.env.GITHUB_RUN_NUMBER}`,
                name: `Release v1.0.${process.env.GITHUB_RUN_NUMBER}`,
                body: `### KSMS Mobile App Release
                
                **Build Information**
                - Version: 1.0.${process.env.GITHUB_RUN_NUMBER}
                - Build Number: ${process.env.GITHUB_RUN_NUMBER}
                - Release Date: ${new Date().toISOString().split('T')[0]}
                
                ### Installation
                
                1. **Scan QR Code**
                ![QRCode](${qrCodeUrl})
                
                2. **Direct Download**
                [![Download APK](https://img.shields.io/badge/Download_APK-blue?style=for-the-badge)](${downloadUrl})
                
                ### Note
                - This is a pre-release version
                - Please report any issues you encounter`,
                draft: false,
                prerelease: true
              });

              if (!releaseResponse.data.id) {
                throw new Error('Failed to create release');
              }
              
              core.info('Uploading APK file...');
              const apkContent = await fs.promises.readFile(apkPath);

              const uploadResponse = await github.rest.repos.uploadReleaseAsset({
                owner: context.repo.owner,
                repo: context.repo.repo,
                release_id: releaseResponse.data.id,
                name: `ksms-mb-v1.0.${process.env.GITHUB_RUN_NUMBER}.apk`,
                data: apkContent
              });

              if (!uploadResponse.data.id) {
                throw new Error('Failed to upload asset');
              }
              
              core.info('Release created successfully');
              
            } catch (error) {
              core.setFailed(`Release creation failed: ${error.message}`);
              throw error;
            }
