name: Expo Android Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    name: Build Expo Android
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          npm install --frozen-lockfile
          npm install -g eas-cli

      # 4. Login to Expo (using token)
      - name: Login to Expo
        run: npx eas login --token "$EXPO_TOKEN"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}  # Best Practice: Use GitHub Secrets

      # 5. Build App (Android)
      - name: Build App (Android)
        run: |
          eas build --platform android \
            --non-interactive \
            --profile production

      # 6. (Optional) Get APK URL / Download Artifact (Improved)
      - name: Parse build result and upload artifact
        id: get-build-url
        run: |
          BUILD_INFO=$(eas build:list --platform android --status finished --limit 1 --json)
          BUILD_URL=$(echo "$BUILD_INFO" | jq -r '.[0].artifacts.buildUrl')
          echo "buildUrl=$BUILD_URL" >> $GITHUB_OUTPUT  # Correct way to set output
        if: ${{ success() }} #Only run if the build succeeded.

      - name: Log build URL
        if: ${{ success() }}
        run: |
          echo "Android Build URL: ${{ steps.get-build-url.outputs.buildUrl }}"
