name: Build and Release Expo App

# Thêm permissions
permissions: 
  contents: write
  issues: write
  pull-requests: write
  discussions: write
  packages: write
  actions: write
  repository-projects: write

on:
  push:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      
      # Thêm cache cho Gradle
      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      # Thêm cache cho Node modules
      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-
          
      - name: Install dependencies
        run: |
          yarn install
          
      - name: Install EAS CLI
        run: npm install -g eas-cli
        
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        
      # Thêm validate Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
        
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          
      - name: Create eas.json
        run: |
          cat > eas.json << 'EOL'
          {
            "cli": {
              "version": ">= 3.13.3",
              "appVersionSource": "remote"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal",
                "android": {
                  "buildType": "apk",
                  "gradleCommand": ":app:assembleDebug"
                }
              },
              "preview": {
                "distribution": "internal",
                "android": {
                  "buildType": "apk"
                }
              },
              "production": {
                "autoIncrement": true,
                "android": {
                  "buildType": "apk"
                }
              }
            }
          }
          EOL
          
      # Thêm bước tạo tag trước khi create release
      - name: Create Tag
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Android app
        run: |
          eas build --local \
          --non-interactive \
          --output=./app-build \
          --platform=android \
          --profile=production
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          
      # Thay thế actions/create-release bằng softprops/action-gh-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            KSMS Mobile App Release
            Build number: ${{ github.run_number }}
          files: ./app-build/*.apk
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generating QR code
        uses: kentaro-m/qr-code-commenter-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          content: https://github.com/nhatsang29/ksms-MB/releases/download/v1.0.${{ github.run_number }}/ksms-mb-v1.0.${{ github.run_number }}.apk
          comment: |
            :lock: Scan QR code below to download KSMS Mobile App :iphone: