name: EAS Build Android

# Trigger workflow khi push, pull request, hoặc kích hoạt thủ công
on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/android-build.yml'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile (development, preview, production)'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

jobs:
  build:
    name: EAS Build Android
    runs-on: self-hosted
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Determine build profile
        id: profile
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "name=${{ github.event.inputs.profile }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "name=production" >> $GITHUB_OUTPUT
          else
            echo "name=preview" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup build directories
        run: |
          mkdir -p $HOME/expo-tmp
          mkdir -p $HOME/eas-builds/working
          mkdir -p $HOME/eas-builds/artifacts
          mkdir -p $HOME/.gradle
          
          # Tạo thư mục lưu trữ APK theo ngày
          BUILD_DATE=$(date +"%Y-%m-%d")
          STORAGE_DIR=$HOME/ksms-builds/$BUILD_DATE
          mkdir -p $STORAGE_DIR
          echo "STORAGE_DIR=$STORAGE_DIR" >> $GITHUB_ENV
          
          # Thiết lập và lưu biến môi trường
          echo "TMPDIR=$HOME/expo-tmp" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_WORKINGDIR=$HOME/eas-builds/working" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_ARTIFACTS_DIR=$HOME/eas-builds/artifacts" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_SKIP_CLEANUP=1" >> $GITHUB_ENV
          echo "GRADLE_USER_HOME=$HOME/.gradle" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
      
      - name: Install dependencies
        run: yarn install
      
      - name: Setup EAS CLI
        run: |
          npm install -g eas-cli
          eas --version
      
      - name: Authenticate with Expo
        run: |
          if [ -n "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "Using EXPO_TOKEN for authentication"
            export EXPO_TOKEN="${{ secrets.EXPO_TOKEN }}"
          else
            echo "EXPO_TOKEN not found, trying username and password authentication"
            npx expo login -u ${{ secrets.EXPO_USERNAME }} -p ${{ secrets.EXPO_PASSWORD }}
          fi
      
      - name: Build Android App
        run: |
          echo "Building Android app with profile: ${{ steps.profile.outputs.name }}"
          eas build --platform android --local --non-interactive --profile=${{ steps.profile.outputs.name }}
      
      - name: Generate build metadata
        run: |
          echo "Build completed at $(date)" > ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
          echo "Profile: ${{ steps.profile.outputs.name }}" >> ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
          echo "Branch: ${{ github.ref }}" >> ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
          echo "Commit: ${{ github.sha }}" >> ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
          echo "Commit message: $(git log -1 --pretty=%B)" >> ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
          echo "Build number: $(date +%Y%m%d%H%M)" >> ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt
      
      - name: Save APK to local storage
        run: |
          # Tìm file APK trong thư mục artifacts
          APK_FILE=$(find ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }} -name "*.apk" | head -n 1)
          
          if [ -n "$APK_FILE" ]; then
            # Tạo tên file với profile và timestamp
            APK_FILENAME="ksms-${{ steps.profile.outputs.name }}-${{ env.BUILD_TIMESTAMP }}.apk"
            
            # Sao chép file APK vào thư mục lưu trữ
            cp "$APK_FILE" "${{ env.STORAGE_DIR }}/$APK_FILENAME"
            cp "${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/build-metadata.txt" "${{ env.STORAGE_DIR }}/metadata-${{ env.BUILD_TIMESTAMP }}.txt"
            
            echo "APK saved to ${{ env.STORAGE_DIR }}/$APK_FILENAME"
            echo "APK_PATH=${{ env.STORAGE_DIR }}/$APK_FILENAME" >> $GITHUB_ENV
          else
            echo "No APK file found in artifacts directory!"
            exit 1
          fi
      
      - name: List saved APKs
        run: |
          echo "=== Recent APK Builds ==="
          find $HOME/ksms-builds -type f -name "*.apk" -mtime -7 | sort -r
