name: EAS Build Android

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/android-build.yml'
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:
    inputs:
      profile:
        description: 'Build profile (development, preview, production)'
        required: true
        default: 'preview'
        type: choice
        options:
          - development
          - preview
          - production

env:
  # Thiết lập biến môi trường toàn cục
  CACHE_LIFETIME_DAYS: 7
  YARN_NETWORK_TIMEOUT: 300000
  GRADLE_MEMORY: "24g"
  GRADLE_MAX_WORKERS: 14
  METRO_MEMORY: "8192"
  PERSISTENT_CACHE_PATH: "~/.eas-build-cache"

jobs:
  build:
    name: EAS Build Android
    runs-on: [google]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Determine build profile
        id: profile
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "name=${{ github.event.inputs.profile }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "name=production" >> $GITHUB_OUTPUT
          else
            echo "name=preview" >> $GITHUB_OUTPUT
          fi
      
      - name: Setup build directories
        run: |
          mkdir -p $HOME/expo-tmp
          mkdir -p $HOME/eas-builds/working
          mkdir -p $HOME/eas-builds/artifacts
          mkdir -p $HOME/gradle-build-cache
          mkdir -p $HOME/.eas-build-cache
          
          # Tạo thư mục lưu trữ APK theo ngày
          BUILD_DATE=$(date +"%Y-%m-%d")
          STORAGE_DIR=$HOME/ksms-builds/$BUILD_DATE
          mkdir -p $STORAGE_DIR
          echo "STORAGE_DIR=$STORAGE_DIR" >> $GITHUB_ENV
          
          # Xóa dữ liệu build cũ
          rm -rf $HOME/eas-builds/working/*
          rm -rf $HOME/expo-tmp/*
          rm -rf $HOME/eas-builds/artifacts/*
          
          # Thiết lập và lưu biến môi trường
          echo "TMPDIR=$HOME/expo-tmp" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_WORKINGDIR=$HOME/eas-builds/working" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_ARTIFACTS_DIR=$HOME/eas-builds/artifacts" >> $GITHUB_ENV
          echo "EAS_LOCAL_BUILD_SKIP_CLEANUP=1" >> $GITHUB_ENV
          echo "BUILD_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")" >> $GITHUB_ENV
          
          # Thiết lập biến môi trường để tận dụng tối đa phần cứng
          GRADLE_MEM="${GRADLE_MEMORY}"
          GRADLE_WORKERS="${GRADLE_MAX_WORKERS}"
          METRO_MEM="${METRO_MEMORY}"
          
          echo "GRADLE_OPTS=-Xmx$GRADLE_MEM -XX:MaxMetaspaceSize=4g -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.jvmargs=-Xmx$GRADLE_MEM -Dorg.gradle.workers.max=$GRADLE_WORKERS -XX:+UseParallelGC" >> $GITHUB_ENV
          
          # Bỏ qua cảnh báo về ký tự $ trong định danh C++
          echo "CFLAGS=-Wno-dollar-in-identifier-extension" >> $GITHUB_ENV

      - name: Restore Yarn cache
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: yarn-cache-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-cache-${{ runner.os }}-

      - name: Restore Gradle cache
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-cache-${{ runner.os }}-${{ hashFiles('**/android/**/build.gradle') }}
          restore-keys: |
            gradle-cache-${{ runner.os }}-

      - name: Restore EAS cache
        uses: actions/cache@v3
        with:
          path: ~/.eas-build-cache
          key: eas-cache-${{ runner.os }}-${{ hashFiles('eas.json') }}
          restore-keys: |
            eas-cache-${{ runner.os }}-

      - name: Setup Android SDK
        run: |
          echo "Setting up Android SDK environment..."
          
          # Dọn dẹp môi trường cũ
          rm -rf $HOME/android-sdk
          
          # Tạo thư mục mới
          mkdir -p $HOME/android-sdk
          
          # Đặt biến SDK_ROOT
          SDK_ROOT=$HOME/android-sdk
          echo "ANDROID_HOME=$SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$SDK_ROOT" >> $GITHUB_ENV
          
          # Cài đặt Android SDK
          cd $SDK_ROOT
          
          # Tạo cấu trúc thư mục đúng cho cmdline-tools
          mkdir -p $SDK_ROOT/cmdline-tools/latest
          
          # Tải và giải nén command line tools vào thư mục tạm
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d temp_dir
          
          # Di chuyển nội dung vào vị trí chính xác
          mv temp_dir/cmdline-tools/* $SDK_ROOT/cmdline-tools/latest/
          
          # Dọn dẹp
          rm -rf temp_dir commandlinetools-linux-9477386_latest.zip
          
          # Thiết lập quyền truy cập
          chmod -R 755 $SDK_ROOT/cmdline-tools
          
          # Chấp nhận licenses
          yes | $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --licenses || true
          
          # Cài đặt packages với retry và verify
          for i in {1..3}; do
            echo "Installing Android packages (Attempt $i)..."
            
            if $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"; then
              echo "Waiting for package installation to complete..."
              sleep 30  # Chờ để đảm bảo cài đặt hoàn tất
              
              # Verify cài đặt
              if $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --list_installed | grep -q "platform-tools"; then
                echo "✅ Platform tools installed successfully"
                break
              fi
            fi
            
            echo "⚠️ Attempt $i failed, retrying after cleanup..."
            rm -rf $SDK_ROOT/platform-tools $SDK_ROOT/build-tools $SDK_ROOT/platforms  # Cleanup failed install
            sleep 10
          done
          
          # Double check installation
          if ! $SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$SDK_ROOT --list_installed | grep -q "platform-tools"; then
            echo "❌ Failed to install Android packages after 3 attempts"
            exit 1
          fi

      - name: Install dependencies
        run: |
          yarn config set network-timeout ${YARN_NETWORK_TIMEOUT}
          yarn install --frozen-lockfile --prefer-offline --network-timeout ${YARN_NETWORK_TIMEOUT} --non-interactive --cache-folder .yarn/cache

      - name: Fix Metro versions
        run: |
          # Fix package versions for Metro
          yarn add metro@^0.81.0 metro-resolver@^0.81.0 metro-config@^0.81.0 --dev

      - name: Build Android App
        run: |
          echo "Building with profile: ${{ steps.profile.outputs.name }}"
          
          # Configure EAS Build
          npx eas-cli build --platform android --profile ${{ steps.profile.outputs.name }} --local --non-interactive
          
          # Copy artifacts
          if [ -d "${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}" ]; then
            cp -r ${{ env.EAS_LOCAL_BUILD_ARTIFACTS_DIR }}/* ${{ env.STORAGE_DIR }}/
            echo "✅ Build artifacts copied to ${{ env.STORAGE_DIR }}"
          else
            echo "❌ No build artifacts found"
            exit 1
          fi

      - name: Clean and monitor caches
        run: |
          echo "🧹 Bắt đầu quá trình dọn dẹp cache..."
          
          # Tạo thư mục log
          LOG_DIR="${{ env.STORAGE_DIR }}/logs/cache"
          mkdir -p "$LOG_DIR"
          MONITOR_LOG="$LOG_DIR/cache-monitor-${{ env.BUILD_TIMESTAMP }}.log"
          
          # Quản lý kích thước cache
          yarn cache clean
          rm -rf $HOME/.gradle/caches/build-cache-*
          
          echo "✅ Cache cleanup completed"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-app-${{ steps.profile.outputs.name }}-${{ env.BUILD_TIMESTAMP }}
          path: ${{ env.STORAGE_DIR }}/*.apk
          retention-days: 7
